"use client";

/**
 * Dependency-free PDF export: opens a print-ready HTML window and triggers
 * the browser's "Save as PDF" dialog. Works for SWOT + Strategy reports.
 */

interface ExportSection {
  heading: string;
  html: string;
}

export function exportReportToPDF(opts: {
  title: string;
  subtitle?: string;
  meta: { label: string; value: string }[];
  sections: ExportSection[];
}) {
  const { title, subtitle, meta, sections } = opts;

  const win = window.open("", "_blank", "width=900,height=1100");
  if (!win) {
    alert("Please allow pop-ups to export the report as PDF.");
    return;
  }

  const metaHtml = meta
    .map(
      (m) =>
        `<div class="meta-item"><span class="meta-label">${escapeHtml(m.label)}</span><span class="meta-value">${escapeHtml(m.value)}</span></div>`,
    )
    .join("");

  const sectionsHtml = sections
    .map(
      (s) =>
        `<section class="section"><h2>${escapeHtml(s.heading)}</h2>${s.html}</section>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html dir="ltr">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(title)}</title>
<style>
  @page { size: A4; margin: 16mm 14mm; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; color: #1a1a2e; margin: 0; padding: 24px; }
  .header { border-bottom: 3px solid #6366f1; padding-bottom: 16px; margin-bottom: 20px; }
  .header h1 { font-size: 26px; margin: 0 0 4px; color: #4338ca; }
  .header .subtitle { color: #6b7280; font-size: 13px; margin: 0 0 12px; }
  .meta { display: flex; flex-wrap: wrap; gap: 8px 20px; }
  .meta-item { display: flex; flex-direction: column; }
  .meta-label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: #9ca3af; }
  .meta-value { font-size: 13px; font-weight: 600; color: #374151; }
  section.section { margin-bottom: 22px; page-break-inside: avoid; }
  section h2 { font-size: 17px; color: #4338ca; border-left: 4px solid #6366f1; padding-left: 10px; margin: 0 0 12px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
  .card { border: 1px solid #e5e7eb; border-radius: 10px; padding: 12px; background: #fafafa; }
  .card h3 { margin: 0 0 6px; font-size: 14px; color: #312e81; }
  .card p { margin: 0; font-size: 12px; color: #4b5563; line-height: 1.5; }
  .tag { display: inline-block; font-size: 10px; padding: 2px 8px; border-radius: 999px; background: #ede9fe; color: #6d28d9; margin-bottom: 6px; }
  .quote { font-style: italic; color: #4338ca; border-left: 3px solid #c4b5fd; padding: 4px 8px; margin: 4px 0; font-size: 12px; }
  .row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px dashed #e5e7eb; font-size: 12px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th, td { text-align: left; padding: 7px 8px; border-bottom: 1px solid #e5e7eb; }
  th { background: #f3f4f6; color: #374151; font-size: 11px; text-transform: uppercase; letter-spacing: 0.3px; }
  .footer { margin-top: 28px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; text-align: center; }
  .badge { display: inline-block; font-size: 10px; font-weight: 700; padding: 2px 7px; border-radius: 6px; }
  .b-p0 { background:#fee2e2;color:#b91c1c;} .b-p1{background:#fef3c7;color:#b45309;} .b-p2{background:#ede9fe;color:#6d28d9;} .b-p3{background:#e0f2fe;color:#075985;}
</style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(title)}</h1>
    ${subtitle ? `<p class="subtitle">${escapeHtml(subtitle)}</p>` : ""}
    <div class="meta">${metaHtml}</div>
  </div>
  ${sectionsHtml}
  <div class="footer">Generated by Business Intelligence Platform — SWOT Agent v7 / Strategy Agent v1 · Vertex AI Gemini 2.5 Flash</div>
  <script>window.onload = () => { setTimeout(() => { window.print(); }, 350); };</script>
</body>
</html>`;

  win.document.open();
  win.document.write(html);
  win.document.close();
}

export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
